#pragma once
#include "BaseStrategy.hpp"
#include <fstream>

class WasmStrategy : public BaseStrategy
{
protected:
    std::string get_source_file_path() const override { return "/tmp/main.cpp"; }
    std::string get_compiled_binary_path() const override { return "/tmp/output.js"; }

    std::vector<std::string> get_compile_command() const override
    {
        return {
            "emcc", 
            "/tmp/main.cpp", 
            "-o", "/tmp/output.js", 
            "-s", "WASM=1", 
            "-s", "SINGLE_FILE=1", // Embeds the WASM binary inside the JS as base64
            "-O3",                 // Maximum optimization for client-side performance
            "-std=c++17"
        };
    }

    std::vector<std::string> get_execute_command() const override
    {
        // WASM is NOT executed on the backend.
        return {};
    }

public:
    ExecutionResult execute(const std::string &source_code, const std::string &stdin_data, int timeout_ms) override
    {
        ExecutionResult result = {0, "", "", 0.0, false, false};
        
        // 1. Read the JavaScript/WASM payload generated by compile()
        result.stdout_output = read_file("/tmp/output.js");
        
        // 2. Clear out any potential temp files to keep the sandbox clean
        std::remove("/tmp/output.js");
        std::remove("/tmp/main.cpp");
        
        if (result.stdout_output.empty()) {
            result.exit_code = 1;
            result.stderr_output = "Failed to generate WASM payload.";
        } else {
            result.exit_code = 0;
            // The JSON orchestrator will serialize stdout_output and send it to the React frontend
        }

        return result;
    }
};
