#pragma once
#include "BaseStrategy.hpp"
#include <fstream>
#include <string>

class WasmRustStrategy : public BaseStrategy
{
protected:
    std::string get_source_file_path() const override { return "/tmp/main.rs"; }
    std::string get_compiled_binary_path() const override { return "/tmp/main.wasm"; }

    std::vector<std::string> get_compile_command() const override
    {
        return {
            "sh", "-c", "export PATH=$PATH:/usr/local/cargo/bin && rustc --target wasm32-unknown-unknown -O /tmp/main.rs -o /tmp/main.wasm"
        };
    }

    std::vector<std::string> get_execute_command() const override
    {
        // WASM is NOT executed on the backend.
        return {};
    }

public:
    ExecutionResult execute(const std::string &source_code, const std::string &stdin_data, int timeout_ms) override
    {
        ExecutionResult result = {0, "", "", 0.0, false, false};
        
        // 1. Read the WASM payload generated by compile()
        std::string raw_wasm = read_file("/tmp/main.wasm");
        result.stdout_output = base64_encode(raw_wasm);
        
        // 2. Clear out any potential temp files to keep the sandbox clean
        std::remove("/tmp/main.wasm");
        std::remove("/tmp/main.rs");
        
        if (result.stdout_output.empty()) {
            result.exit_code = 1;
            result.stderr_output = "Failed to generate WASM payload from Rust code.";
        } else {
            result.exit_code = 0;
            // The JSON orchestrator will serialize stdout_output as base64 or raw string
        }

        return result;
    }
};
